### ISSUE TITLE
Cooldown skippable

### ISSUE THREAD

**Issue by dieflemm** [RasaNovum/Via_Romana#10]
The teleportation cooldown potion effect can be skipped/removed with a milk bucket or similar which remove potion effects. Would it be possible to change it that you cant remove the cooldown effect? Or is this intended?

Versions used: Minecraft 1.20.1, Forge 47.2.0, Via Romana 1.1.3

**Comment by xameryn** [comment]
It's not intended but was never really seen as an issue since the cooldown by default is so quick. Ideally it shouldn't be skippable so I'll keep this open as enhancement.

**Comment by xameryn** [comment]
Fixed internally, will roll out in next update.

**Comment by xameryn** [comment]
Just released v1.2 which fixes this 🫡
https://modrinth.com/mod/via-romana/version/1.2
