### ISSUE TITLE
Block whitelist instead of tag

### ISSUE THREAD

**Issue by zackadiax24** [RasaNovum/Via_Romana#11]
If possible I believe having a customizable whitelist, possibly via config or possibly via command (or both) would make this mod much more usable with other mods. As an example, i want to use the path blocks from rechiseled but i can because they lack a unique tag. If I tried to use one of the tags available it would make almost every block in the game a "path block".

**Comment by xameryn** [comment]
Hey, this can already be done using KubeJS as shown [in our wiki](https://github.com/RasaNovum/Via_Romana/wiki). If this isn't what you mean I'll re-open the issue.

**Comment by xameryn** [comment]
Just released v1.2 which adds block ID whitelisting via config 🫡
https://modrinth.com/mod/via-romana/version/1.2
