### ISSUE TITLE
Eating from off-hand breaks the mod

### ISSUE THREAD

**Issue by spongebobsqrhed** [RasaNovum/Via_Romana#14]
When you eat food from your off-hand, you can no longer travel or chart paths
NeoForge v47.1.106 Via Romana v1.1.3
Video showing the issue: https://youtu.be/me3HJKnEtLs

**Comment by xameryn** [comment]
Craziest bug so far, thanks for the video, was able to recreate it and am working on it 🫡

**Comment by xameryn** [comment]
Fixed internally, will roll out in next update.

**Comment by dandy-is-lion** [comment]
Wow nice find! Was wondering why it would stop working after awhile and I'd have to relog. I always eat from my offhand but didn't make the connection. Was thinking it was a game desync or something. Awesome mod btw!

**Comment by xameryn** [comment]
Just released v1.2 which fixes this 🫡
https://modrinth.com/mod/via-romana/version/1.2

**Comment by dandy-is-lion** [comment]
Actually goated. Thanks so much!
