### ISSUE TITLE
[1.20.1-1.2] Spam "Message"

### ISSUE THREAD

**Issue by DankestO** [RasaNovum/Via_Romana#16]
In the last update, in the dedicated server console I constantly see:
[Server thread/INFO] [ne.ra.vi.ViaRomanaMod/]: Message

Should I disable something to avoid this? I don't see anything like that in the configs.

**Comment by xameryn** [comment]
Uh oh, probably forgot to remove a debug message, will look into it.

**Comment by xameryn** [comment]
Thanks, fixed in v1.2.1🫡
https://modrinth.com/mod/via-romana/version/1.2.1

**Comment by DankestO** [comment]
Thanks! :D
