### ISSUE TITLE
Potential issue with game tick

### ISSUE THREAD

**Issue by Mouteg** [RasaNovum/Via_Romana#6]
My server just crashed with server tick being too long. Possibly cause of your mod, but not necesserily.
Via Romana (via_romana), Version: 1.1.2
		at TRANSFORMER/via_romana@1.1.2/net.rasanovum.viaromana.procedures.IsTopSignProcedure.execute(IsTopSignProcedure.java:53)

[crash-2024-06-05_23.05.10-server.txt](https://github.com/user-attachments/files/15587398/crash-2024-06-05_23.05.10-server.txt)

**Comment by xameryn** [comment]
Looks like Via Romana's fault, were you doing anything with it at the time (charting, teleporting, etc.) or did it just happen randomly?

**Comment by xameryn** [comment]
Actually I think I found the issue, should be fixed now, will send out the update. Thanks for reporting🫡

**Comment by Mouteg** [comment]
Thanks for a quick fix, to answer your question, i did not do anything with the mod at that moment and i did not have any mapped routes or anything.
