### ISSUE TITLE
[1.20.1] Remove "Path Underdeveloped" when back on developed ground

### ISSUE THREAD

**Issue by DankestO** [RasaNovum/Via_Romana#7]
Hi!, I am using "Macaw's Paths and Pavings", when there are very steep stairs the path is no longer recognized, how can I solve that?

![Captura de pantalla 2024-06-12 220236](https://github.com/RasaNovum/Via_Romana/assets/126206944/62d7b401-450b-4991-a174-65cd25fe82e8)

**Comment by DankestO** [comment]
Somehow I managed to join both signals, even though it told me that it was "path underdeveloped", it must be my fault that I didn't understand something xD

**Comment by xameryn** [comment]
Ah I think this occurs because the "path underdeveloped" message stays visible for a while before disappearing and is only forcibly removed if another condition takes over (ie. Too far off trail/charting...), I'll look into fixing that.

**Comment by xameryn** [comment]
Fixed internally, will roll out in next update.

**Comment by xameryn** [comment]
Just released v1.2 which fixes this 🫡
https://modrinth.com/mod/via-romana/version/1.2
